#Publish to PowerShell Gallery with this key (AutomatedLab account)
environment:
  NuGetApiKey:
    secure: C6W1vuS0plyq7Z5uaWsTTCIZw7tSLYOyNw3rTujn9C0+/u4BCJ3+aEflh0V6kXN9

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1
