#Publish to PowerShell Gallery with this key (AutomatedLab account)
environment:
  NuGetApiKey:
    secure: tAdUQmRiZ270LOPN8SwbjISLfu6ldDTw6LWvdtsk+pQR7r5bJnGrG8Ntyt87edJ/

version: 2.0.{build}

skip_tags: true
skip_branch_with_pr: true

image: Visual Studio 2017

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

before_test:
  - nuget restore
  - ps: |
        Write-Host "'before_build' block"

        Write-Host "Setting version number in files"
        Add-AppveyorMessage -Message "Setting version number in files" -Category Information
        gci -Filter *.psd1 -Recurse | foreach {(Get-Content $_.FullName -Raw) -replace "ModuleVersion += '\d\.\d\.\d'", "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'" | Out-File $_.FullName}


#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1
