on: [pull_request]

jobs:
  validate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: ./build/vsts-prerequisites.ps1
      shell: pwsh
    - name: Build
      run: ./build/vsts-build.ps1 -SkipPublish -LocalRepo
      shell: pwsh
    - name: Validate
      run: ./build/vsts-validate.ps1
      shell: pwsh